"""add Note and Entry tables

Revision ID: 10df5788dfa5
Revises: 
Create Date: 2021-07-15 22:20:56.164699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10df5788dfa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('language', sa.Enum('english', 'french', 'german', name='language'), nullable=False),
    sa.Column('audio_file', sa.String(), nullable=True),
    sa.Column('image_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('entry')
    # ### end Alembic commands ###
